### ISSUE TITLE
Support other platforms with CMake build script.

### ISSUE THREAD

**Issue by Pwera** [besh81/nana-creator#2]
```
project(nana-creator)
cmake_minimum_required(VERSION 2.8)
include_directories(${CMAKE_SOURCE_DIR}/src)
include_directories(${CMAKE_SOURCE_DIR}/src/ctrls)
include_directories(${CMAKE_SOURCE_DIR}/libs)
add_executable(nana-creator src/ctrls/button.cpp src/ctrls/combox.cpp src/ctrls/label.cpp src/ctrls/layout.cpp src/ctrls/panel.cpp src/ctrls/property.cpp src/ctrls/spinbox.cpp src/ctrls/textbox.cpp src/nana_extra/pg_items.cpp src/nana_extra/propgrid.cpp src/assetspanel.cpp src/codegenerator.cpp src/guimanager.cpp src/main.cpp src/namemanager.cpp src/objectspanel.cpp src/propertiespanel.cpp src/resizablecanvas.cpp libs/pugixml/pugiconfig.hpp libs/pugixml/pugixml.cpp libs/pugixml/pugixml.hpp )
set_property(TARGET nana-creator PROPERTY CXX_STANDARD 11)
target_link_libraries(nana-creator nana)
```

**Comment by besh81** [comment]
Hi Pwera

I really don't know how to use CMake so if you want to contribute please tell me what to do with the script you suggested.

Ciao

**Comment by szega83** [comment]
Hi Besh!

I'm having difficulties building nana-creator on Linux.
Here are some of the errors, with my -sometimes questionable- solutions:
```
codegenerator.cpp:133:17: error: ‘strlen’ is not a member of ‘std’
codegenerator.cpp:150:34: error: ‘strlen’ is not a member of ‘std’
my solution: #include <cstring>

ctrl.cpp:184:94: error: expected primary-expression before ‘unsigned’
my solution: use static_cast<unsigned int>

tabbar.cpp:44:16: error: ‘using event_type = struct nana::drawerbase::tabbar::tabbar_events<long unsigned int> {aka struct nana::drawerbase::tabbar::tabbar_events<long unsigned int>}’ has no member named ‘adding’; did you mean ‘added’?
my solution: use added

tabbar.cpp:44:41: error: ‘arg_tabbar_adding’ in namespace ‘nana’ does not name a template type
my solution: no idea. I just renamed it ‘arg_tabbar' and commented out "arg.add = false;"

filemanager.cpp:167:14: error: aggregate ‘file_exists(const string&)::stat buffer’ has incomplete type and cannot be defined
my solution: for linux, also #include <sys/stat.h>

items_dialog.cpp:131:35: error: cannot bind non-const lvalue reference of type ‘nana::drawerbase::treebox::item_proxy&’ to an rvalue of type ‘nana::treebox::item_proxy {aka nana::drawerbase::treebox::item_proxy}’
src/items_dialog.cpp:141:36: error: cannot bind non-const lvalue reference of type ‘nana::drawerbase::treebox::item_proxy&’ to an rvalue of type ‘nana::treebox::item_proxy {aka nana::drawerbase::treebox::item_proxy}’
my solution: dereference operator missing --> *items_tree.selected()

items_dialog.cpp:422:18: error: ‘class __gnu_cxx::__normal_iterator<items_dialog::_data_struct*, std::vector<items_dialog::_data_struct> >’ has no member named ‘_Ptr’
my solution: i._Ptr works only on MSVC. Use &(*i);

src/main.cpp:30:12: error: ‘::main’ must return ‘int’
solution: int main()
```
Now it compiles, but
I'm still facing a *single* linking error (to stdc++fs), I cannot solve.
`undefined reference to 'std::experimental::filesystem::v1::__cxx11::filesystem_error::_M_gen_what()'`

Do you have an idea how to fix this?

**Comment by besh81** [comment]
Hi szega83

Thanks for the feedback. 
I'm going to fix all the issues you found in the next release.

To solve the tabbar issues you should download nanalib 1.6.2 hotfix or 1.7
Adding is a new event I added

Unfortunately I don't have any idea how to solve that last linking error.
Are u using Ubuntu or what? 
How do you build the lib and the creator?

**Comment by szega83** [comment]
I fixed that linking error, by using the same compiler flags as nana uses within it's makefile.
(I had to add -std=c++11, otherwise it couldn't link `std::experimental::filesystem::v1::__cxx11`,
than I simply replaced the c++17 algorithm you used with a raw for-loop)

I'm using Ubuntu 18.04, I build nana with the makefile they provide, and for nana-creator,  
here is my ugly-but-works-on-my-machine CMakeList:
[CMakeLists.txt](https://github.com/besh81/nana-creator/files/2591701/CMakeLists.txt)

Now it compiles, links, and runs,
but throws a segmentation fault while calling guimanager's constructor.
```
Core was generated by `./nana_creator'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005564e91a9678 in nana::detail::platform_spec::open_display (this=0x0)
    at ../../source/detail/platform_spec_posix.cpp:537
537                     return display_;
(gdb) bt
#0  0x00005564e91a9678 in nana::detail::platform_spec::open_display (this=0x0)
    at ../../source/detail/platform_spec_posix.cpp:537
#1  0x00005564e9166eb1 in nana::detail::native_interface::primary_monitor_size ()
    at ../../source/gui/detail/native_window_interface.cpp:259
#2  0x00005564e9156333 in nana::screen::primary_monitor_size () at ../../source/gui/screen.cpp:87
#3  0x00005564e908e65a in nana::drawerbase::menu::menu_builder::menu_builder (this=0x5564eb107290, 
    owner=0x5564e95a9848 <g_gui_mgr+8>) at ../../source/gui/widgets/menu.cpp:175
#4  0x00005564e909134d in nana::menu::implement::implement (this=0x5564eb107290, self=0x5564e95a9848 <g_gui_mgr+8>)
    at ../../source/gui/widgets/menu.cpp:1130
#5  0x00005564e908c655 in nana::menu::menu (this=0x5564e95a9848 <g_gui_mgr+8>)
    at ../../source/gui/widgets/menu.cpp:1136
#6  0x00005564e8f725e1 in guimanager::guimanager (this=0x5564e95a9840 <g_gui_mgr>) at ../src/guimanager.cpp:59
#7  0x00005564e8f94cc8 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535)
    at ../src/main.cpp:15
#8  0x00005564e8f94d9b in _GLOBAL__sub_I_g_gui_mgr () at ../src/main.cpp:61                                             
#9  0x00005564e922792d in __libc_csu_init ()
#10 0x00007f86b26a1b28 in __libc_start_main (main=0x5564e8f93686 <main()>, argc=1, argv=0x7ffdb98826a8, 
    init=0x5564e92278e0 <__libc_csu_init>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdb9882698)
    at ../csu/libc-start.c:266
#11 0x00005564e8f1db6a in _start ()
```

I'm not sure why, but I'll figure it out. 
For me, there's a lot to learn about c++.

Thanks for your help!
